/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData gau = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData gauf = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData matic = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData usdc = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData usdt = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData eth = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData link = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData crv = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData wbtc = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData group_46 = IconData(0xe80a, fontFamily: _kFontFam);
}
